name: austin_small_talk
description: "A new Flutter project."
publish_to: 'none'  # Remove this line if you want to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  go_router: ^14.6.2
  get: ^4.6.6
  flutter_screenutil: ^5.9.0
  image_picker: ^1.1.2
  flutter_svg: ^2.0.10
  socket_io_client: ^2.0.0
  shimmer: ^3.0.0
  cached_network_image: ^3.3.1
  connectivity_plus: ^6.1.0
  shared_preferences: ^2.2.3
  intl: ^0.20.2
  google_fonts: ^6.2.1
  flutter_spinkit: ^5.2.0
  fluttertoast: ^8.2.4
  flutter_tts: ^4.0.2
  permission_handler: ^11.3.1
  device_preview: ^1.1.0
  speech_to_text: ^7.3.0
  wave_blob: ^1.0.5
  animated_text_kit: ^4.2.2
  http: ^1.2.0
  toastification: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/main_logo.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/images/main_logo.png"
    background_color: "#FFFFFF"
    theme_color: "#000000"
  windows:
    generate: true
    image_path: "assets/images/main_logo.png"
    icon_size: 40
  macos:
    generate: true
    image_path: "assets/images/main_logo.png"

flutter:
  uses-material-design: true

  assets:
    # Include entire directory for images
    - assets/images/

    # Include entire directory for icons (if you use any other icons)
    - assets/icons/
